name: Account_book CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 工作流包含的任务 (jobs)
jobs:
  build-and-test:
  # 运行此任务的操作系统环境
    runs-on: ubuntu-latest
  # 任务包含的步骤 (steps)
    steps:
    # 第一步：检出你的代码库
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
        python-version: "3.10"
    # 第三步：安装项目依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 假设你的依赖项在 requirements.txt 中
        pip install pytest # 安装测试框架
    # 第四步： 进行单元测试检测两个子功能
    - name: Run unit tests with pytest
      run: |
        python3 -m pytest tests/test_get_records_by_date_range.py tests/test_predict_future.py -v
    # 第五步：进行集成测试
    - name: Run integration tests with pytest
      run: |
        python3 -m pytest tests_integration/ -v
    
